### ISSUE TITLE
The values of any Page returned are all always null

### ISSUE THREAD

**Issue by Adel-Wehbe** [sromku/android-simple-facebook#314]
I tried using mSimpleFacebook.getPages(onPagesListener) or mSimpleFacebook.getMovies(onPagesListener).
They both return a list with the correct number of pages in it. For instance, i liked two movie pages so i get two pages instance in my list. However, all the values of any page (id, name, likes...) are always null. For example, movies.getName() and movies.getId() return null, as do all the other values. It's very frustrating. what can be going wrong? 
Also, my privacy settings on facebook are all public.

**Comment by sromku** [comment]
@Adel-Wehbe It is very strange, because if you get for example 2 pages you likes in result, then at least `id` must exist for each `Page`. Please, check latest build first : https://github.com/sromku/android-simple-facebook#latest-release and retest. Let me know if you have the same issue. 
Thanks, Roman

**Comment by Adel-Wehbe** [comment]
Dear Roman,

The problem did not turn out to be in your code, which is amazing and
extremely simple I must add.

Turns out that requesting page likes requires that an app be reviewed and
accepted by Facebook beforehand. I figured that out when the code used to
work when requesting first name, last name, and birthdays (which do not
require revision by Facebook).

What I did to solve the problem temporary for development purposes is that
i went to the app page on Facebook and added myself and my partner as app
Testers (Developer can work too). In doing so, Facebook did send Facebook
likes whenever either of us used the app.

It was a little confusing because the array that I used to receive had the
correct number of Page objects, except they were empty.

I would like to thank you for your support and for code.

With Regards,
Mr. Adel Dirar Wehbi.
Saida, Lebanon.

**Comment by sromku** [comment]
Mr. Adel Dirar Wehbi, Thanks a lot for your detailed explanation! 
Glad that the issue was resolved and I agree that in some cases it's just not clear what is the reason.
I think that it will be good to add some kind of wiki page that will summarize possible use cases. I will update the wiki.
Much thanks! Roman
